// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyccdypxoijdyguglxkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5Y2NkeXB4b2lqZHlndWdseGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTUyOTAsImV4cCI6MjA2MjgzMTI5MH0.ZeDXZ64mKHbMM4ikDUSHv-JL6OdqJ2w5M-Vkp7gx-jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);