// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkupepbuuqmrimetbang.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdXBlcGJ1dXFtcmltZXRiYW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTQ2MjEsImV4cCI6MjA2Mzc5MDYyMX0.k5eozRozl4Ies3aofTis6Q6AxnAMqvLA3GFLd2Ft88w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);